### ISSUE TITLE
Setup Wordpress theme testing

### ISSUE THREAD

**Issue by AlphaGit** [AlphaGit/alphasmanifesto#10]
More information: http://codex.wordpress.org/Theme_Unit_Test

Make it as automatic as possible.

**Comment by heywin** [comment]
Hi,

I want to get these markdown source code files:
Theme Testing Process
Template File Checklist
Template Hierarchy Index Pages

Could you share it for me? If you would like, you can send it to heywin#gmail.com

Thanks very much.

**Comment by AlphaGit** [comment]
@heywin Sent! I also made them available at [this public gist](https://gist.github.com/AlphaGit/e59afe2e9666708e3295).

**Comment by AlphaGit** [comment]
Testing can be viewed at http://blog-qa.alphasmanifesto.com/

**Comment by AlphaGit** [comment]
## Validate HTML and CSS

(From [Validating a Website / Validation checklist](http://codex.wordpress.org/Validating_a_Website#Validation_Checklist))

- [ ] Validate HTML
- [ ] Validate CSS
- [ ] Validate for Section 508 Standards (accessibility)
- [ ] Validate for WAI standards (accessibility)
- [ ] Validate Links (check for [dead links](http://codex.wordpress.org/WordPress_Site_Maintenance))
- [ ] Validate Feeds
- [ ] Check across different browsers (include handheld computers, Mac, PC, and cellphones, too)

**Comment by AlphaGit** [comment]
IE: Verified compatibility with IE8+.

**Comment by AlphaGit** [comment]
Safari: Verified compatibility with Safari 5+

**Comment by AlphaGit** [comment]
Android: Android 4.4+
Firefox: 30+

**Comment by AlphaGit** [comment]
iPhone Safari: iOS 7.1+

**Comment by AlphaGit** [comment]
Submitted for theme review at https://themes.trac.wordpress.org/ticket/28677

**Comment by AlphaGit** [comment]
(The rest of the submission is out of scope for this ticket. Closing.)
